### Torch Tensor Playground

Basic "w3 school" tutorial
https://deeplizard.com/learn/video/fCVuiW9AFzY

Reference Doc
https://pytorch.org/docs/stable/torch.html
    


In [4]:
import torch
from torch import tensor

In [5]:
tensor([1,2])

tensor([1, 2])

In [8]:
t = tensor([[1,1,1,1],[2,2,2,2],[3,3,3,3]], dtype=torch.float32)

In [10]:
t.size()

torch.Size([3, 4])

In [11]:
t.shape

torch.Size([3, 4])

In [12]:
len(t)

3

In [13]:
t.numel()

12

In [15]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [16]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])