### `init-weights-1`: How to change the init of the layers
In this notebook, we just look at some basic getting/setting of nn layer weights.

In [12]:
import os, sys
import copy as copyroot
import pandas as pd
from IPython.display import display
from matplotlib import pyplot as plt
from fastai.basics import *
from fastai.vision.all import *
import torch
from module2.mnist_helpers import build_df, seed_everything, build_dls
from module2.mnist_models import FeatsNet

In [ ]:
# %load_ext autoreload
# %autoreload 2
# torch.backends.cudnn.deterministic = True
# torch.backends.cudnn.benchmark = True

### Traditional Workflow

In [13]:
path = untar_data(URLs.MNIST_TINY)
df = build_df(path)

dls_tl = build_dls(target='topleft')

In [16]:
fn = FeatsNet(feats=['pts12', 'pts22'])
learn = Learner(dls_tl, 
                fn,
                loss_func=MSELossFlat(), 
                y_range=(-1.,1.),
                metrics=[R2Score()],             
               )

In [17]:
learn.fit(5,lr=2e-2)

In [31]:
[param.shape for param in params]

[torch.Size([28, 64]), torch.Size([28]), torch.Size([2, 28])]

### Setting Weights Manually - OneLayer

In [73]:
model = FeatsNet(H=4, feats=['pts11'])

In [74]:
sd = model.linear1.state_dict()
sd2 = OrderedDict()
for k,v in sd.items():
    sd2[k] = v.zero_()

In [75]:
model.linear1.load_state_dict(sd2)

<All keys matched successfully>

### Setting Weights Manually - All Layers

In [76]:
model = FeatsNet(H=4, feats=['pts11'])

In [78]:
sd = model.state_dict()
for k in sd.keys():
    sd[k].zero_()

In [79]:
model.load_state_dict(sd)

<All keys matched successfully>

In [80]:
list(model.parameters())

[Parameter containing:
 tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]], requires_grad=True),
 Parameter containing:
 tensor([0., 0., 0., 0.], requires_grad=True),
 Parameter containing:
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]], requires_grad=True)]

In [92]:
def zero_p(nn_module, epsilon=1e-6):
    sd = nn_module.state_dict()
    for k in sd.keys(): 
        sd[k].zero_()
        sd[k] += epsilon
    nn_module.load_state_dict(sd)
    return nn_module

### Try fitting the zero init

In [94]:
fn = FeatsNet(feats=['pts12', 'pts22'])
fn = zero_p(fn)

In [95]:
# list(fn.parameters())

In [96]:
learn = Learner(dls_tl, 
                fn,
                loss_func=MSELossFlat(), 
                y_range=(-1.,1.),
                metrics=[R2Score()],             
               )

In [97]:
learn.fit(5,lr=2e-2)