In [1]:
import torch

In [3]:
a = torch.tensor([3.,1.,7.,2.])
a

tensor([3., 1., 7., 2.])

In [4]:
l1 = torch.nn.Linear(4,4)

In [6]:
l1.weight

Parameter containing:
tensor([[ 0.1559,  0.2444,  0.0219,  0.3019],
        [-0.0044, -0.2725, -0.0452, -0.2927],
        [-0.1052, -0.4024, -0.4463, -0.1241],
        [ 0.3514,  0.1711, -0.3530, -0.2919]], requires_grad=True)

In [5]:
l1(a)

tensor([ 1.9023, -1.3174, -4.4774, -1.4514], grad_fn=<AddBackward0>)

In [7]:
c1 = torch.nn.Conv1d(in_channels=1, out_channels=1, 
                     kernel_size=1, stride=1, padding=0)

In [13]:
c1.state_dict()

OrderedDict([('weight', tensor([[[0.2517]]])), ('bias', tensor([0.6599]))])

In [14]:
c1(a.unsqueeze(0).unsqueeze(0))

tensor([[[1.4149, 0.9116, 2.4217, 1.1632]]], grad_fn=<SqueezeBackward1>)

In [15]:
m1 = torch.nn.MaxPool1d(kernel_size=2, stride=None, padding=0)

In [19]:
m1(a.unsqueeze(0).unsqueeze(0))

tensor([[[3., 7.]]])

In [22]:
m1 = torch.nn.MaxPool1d(kernel_size=2, stride=None, padding=1)

m1(a.unsqueeze(0).unsqueeze(0))

tensor([[[3., 7., 2.]]])

In [29]:
m2 = torch.nn.MaxPool1d(kernel_size=2, stride=None, padding=0)

out = m1(a.unsqueeze(0).unsqueeze(0))
out  
# m2(m1(a.unsqueeze(0).unsqueeze(0)).unsqueeze(0).unsqueeze(0))

tensor([[[3., 7., 2.]]])

In [30]:
m2(out)

tensor([[[7.]]])

In [31]:
m1(m1(a.unsqueeze(0).unsqueeze(0)))

tensor([[[3., 7.]]])

In [32]:
from fastai2.vision.all import *

In [35]:
m = resnet18()

In [37]:
type(m)


torchvision.models.resnet.ResNet

In [71]:
[m for m in m.modules()][-7]

Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)

In [41]:
m.layer1

Sequential(
  (0): BasicBlock(
    (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (1): BasicBlock(
    (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
)

In [44]:
from module.mnist_helpers import build_dls

In [45]:
dls = build_dls()

In [46]:
dls

In [47]:
learn = cnn_learner(dls, resnet18, )

In [73]:
x, y = dls.one_batch()

In [78]:
learn.model(x[:2])

tensor([[ 1.9517,  1.4809],
        [-4.6484, -0.9688]], grad_fn=<MmBackward>)

In [81]:
c1 = learn.model[0][0]

In [82]:
c1

Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)

In [84]:
c1.weight.shape

torch.Size([64, 3, 7, 7])

In [72]:
learn.model

Sequential(
  (0): Sequential(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (4): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  

In [51]:
type(learn.model)

torch.nn.modules.container.Sequential

In [85]:
a

tensor([3., 1., 7., 2.])

In [86]:
n = len(a)
cc1 = torch.nn.Conv1d(1, n, kernel_size=2)

In [91]:
cc1.weight

Parameter containing:
tensor([[[-0.5811, -0.0319]],

        [[ 0.1050,  0.1247]],

        [[ 0.2013,  0.1515]],

        [[ 0.4873,  0.5828]]], requires_grad=True)

In [87]:
aa = a.unsqueeze(0).unsqueeze(0)

In [88]:
cc1(aa)

tensor([[[-1.3884, -0.4173, -3.7449],
         [ 0.1539,  0.6923,  0.6986],
         [ 0.0754,  0.5816,  1.0322],
         [ 1.6428,  4.1650,  4.1746]]], grad_fn=<SqueezeBackward1>)

In [92]:
cc2 = torch.nn.Conv1d(1, n, kernel_size=2, padding=1)
cc2.weight.shape

torch.Size([4, 1, 2])

In [110]:
cc3 = torch.nn.Conv1d(1, n, kernel_size=n, padding=0, bias=False)
cc3.weight.shape

torch.Size([4, 1, 4])

In [111]:
sd = cc3.state_dict()

idm = torch.eye(4).unsqueeze(0).permute((1,0,2))

sd['weight'] = torch.nn.Parameter(idm)

cc3.load_state_dict(sd)

<All keys matched successfully>

In [117]:

imdt

tensor([[[0., 1., 1., 1.]],

        [[1., 0., 1., 1.]],

        [[1., 1., 0., 1.]],

        [[1., 1., 1., 0.]]])

In [119]:
idmt = torch.ones_like(idm) - idm

sd = cc3.state_dict()
sd['weight'] = torch.nn.Parameter(idmt)
cc3.load_state_dict(sd)

cc3(aa)

tensor([[[10.],
         [12.],
         [ 6.],
         [11.]]], grad_fn=<SqueezeBackward1>)

In [120]:
mm3 = torch.nn.MaxPool1d(n)

In [123]:
aa.shape

torch.Size([1, 1, 4])

In [122]:
mm3(aa)

tensor([[[7.]]])

In [124]:
cc3(aa).shape

torch.Size([1, 4, 1])

In [129]:
m = torch.nn.MaxPool1d(1)

In [130]:
bb=cc3(aa)
bb

tensor([[[10.],
         [12.],
         [ 6.],
         [11.]]], grad_fn=<SqueezeBackward1>)

In [1]:
1+1

2

In [ ]:
torch.nn.

In [133]:
m = torch.nn.MaxPool1d(4)
cc = m(bb.permute((0,2,1)))
cc

tensor([[[12.]]], grad_fn=<SqueezeBackward1>)

In [135]:
dd = bb - cc
dd

tensor([[[-2.],
         [ 0.],
         [-6.],
         [-1.]]], grad_fn=<SubBackward0>)

In [147]:
ee = dd.clamp(0, -1) * -1
ee

tensor([[[-0.],
         [1.],
         [-0.],
         [-0.]]], grad_fn=<MulBackward0>)

In [143]:
aa

tensor([[[3., 1., 7., 2.]]])

In [145]:
aa @ ee

tensor([[[1.]]], grad_fn=<UnsafeViewBackward>)

In [160]:
m = torch.nn.MaxPool1d(2, padding=0, stride=1, )

In [161]:
m

MaxPool1d(kernel_size=2, stride=1, padding=0, dilation=1, ceil_mode=False)

In [166]:
s = torch.nn.Softmax(dim=2)

In [167]:
s(aa)

tensor([[[0.0178, 0.0024, 0.9732, 0.0066]]])

In [168]:
aa

tensor([[[3., 1., 7., 2.]]])

In [172]:
cc4 = torch.nn.Conv1d(4, 4*4, 4, )

Conv1d(1, 4, kernel_size=(4,), stride=(1,), bias=False)

In [ ]:
1000
1100
1010
1001
1101
1111

In [173]:
from itertools import combinations

In [179]:
list(combinations([1,2,3,4],4))
list(combinations([1,2,3,4],3))

[(1, 2, 3), (1, 2, 4), (1, 3, 4), (2, 3, 4)]

In [195]:
s(torch.tensor([[[0.,1.,.2]]]))

tensor([[[0.2024, 0.5503, 0.2473]]])

In [196]:
from itertools import permutations

In [199]:
list(permutations([1,2,3,4], 4))

[(1, 2, 3, 4),
 (1, 2, 4, 3),
 (1, 3, 2, 4),
 (1, 3, 4, 2),
 (1, 4, 2, 3),
 (1, 4, 3, 2),
 (2, 1, 3, 4),
 (2, 1, 4, 3),
 (2, 3, 1, 4),
 (2, 3, 4, 1),
 (2, 4, 1, 3),
 (2, 4, 3, 1),
 (3, 1, 2, 4),
 (3, 1, 4, 2),
 (3, 2, 1, 4),
 (3, 2, 4, 1),
 (3, 4, 1, 2),
 (3, 4, 2, 1),
 (4, 1, 2, 3),
 (4, 1, 3, 2),
 (4, 2, 1, 3),
 (4, 2, 3, 1),
 (4, 3, 1, 2),
 (4, 3, 2, 1)]

In [202]:
zz = torch.zeros((3,5), requires_grad=True)
zz

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)

In [211]:
zz.scatter(0,torch.tensor([[3], [2]]), 2.)

RuntimeError: Expected tensor [3, 5] and index [2, 1] to have the same size in dimension 0

In [183]:
def foo():
    return [[1] ]+ [[2]]

In [184]:
foo()

[[1], [2]]